"""empty message

Revision ID: a25ddc759e39
Revises: 
Create Date: 2023-05-30 20:13:23.345510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a25ddc759e39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recarga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operadora', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('usada', sa.Boolean(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('data_ganho', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recargas')
    with op.batch_alter_table('estatistica', schema=None) as batch_op:
        batch_op.alter_column('operadora',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('resultado',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('data_ganho')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estatistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_ganho', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False))
        batch_op.alter_column('resultado',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('operadora',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    op.create_table('recargas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('operadora', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('valor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('usada', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('codigo', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('data_ganho', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('recarga')
    # ### end Alembic commands ###
