"""empty message

Revision ID: c7703cbf84d2
Revises: a25ddc759e39
Create Date: 2023-05-30 20:26:15.632021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7703cbf84d2'
down_revision = 'a25ddc759e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estatistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_ganho', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estatistica', schema=None) as batch_op:
        batch_op.drop_column('data_ganho')

    # ### end Alembic commands ###
